In [1]:
import numpy as np
import math
from scipy.spatial.transform import Rotation as R

Problem 2

1. The norm $\| \frac{p+q}{2} \|$ is $\frac{\sqrt5}{2\sqrt2}$ .\
 The quaternion $r$ is $(\frac{2}{\sqrt5}, \frac{1}{\sqrt5}i)$, which is equal to $\frac{2\sqrt2}{\sqrt5 }*\frac{p+q}{2}$.\
T

In [2]:
r = R.from_quat([1/math.sqrt(5),0,0,2/math.sqrt(5)])
print(r.as_matrix())
print(r.as_euler('xyz',degrees=True))

[[ 1.   0.   0. ]
 [ 0.   0.6 -0.8]
 [ 0.   0.8  0.6]]
[53.13010235  0.          0.        ]


2.

In [3]:
def skew_symmetric(array):
    return np.array([[0, -array[2], array[1]], [array[2], 0, -array[0]], [-array[1], array[0], 0]])
# print(np.identity(3) + np.sin(np.pi/2)*skew_symmetric([1,0,0]) + (1-np.cos(np.pi/2))*skew_symmetric([1,0,0])**2)
# print(np.identity(3) + np.sin(np.pi/2)*skew_symmetric([0,1,0]) + (1-np.cos(np.pi/2))*skew_symmetric([0,1,0])**2)
p = R.from_quat([1/math.sqrt(2),0,0,1/math.sqrt(2)])
q = R.from_quat([0,1/math.sqrt(2),0,1/math.sqrt(2)])
print(p.as_rotvec())
print(q.as_rotvec())
print(np.pi/2)

[1.57079633 0.         0.        ]
[0.         1.57079633 0.        ]
1.5707963267948966


3.

(a)

In [4]:
print('p: ',skew_symmetric([1,0,0]))
print('p: ',skew_symmetric([0,1,0]))

p:  [[ 0  0  0]
 [ 0  0 -1]
 [ 0  1  0]]
p:  [[ 0  0  1]
 [ 0  0  0]
 [-1  0  0]]


In [5]:
print(p.as_matrix())
print(q.as_matrix())
# p_skew = skew_symmetric()

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]


In [6]:
print(np.identity(3) + np.sin(np.pi/2)*skew_symmetric([1,0,0]) + (1-np.cos(np.pi/2))*skew_symmetric([1,0,0])@skew_symmetric([1,0,0]))
print(np.identity(3) + np.sin(np.pi/2)*skew_symmetric([0,1,0]) + (1-np.cos(np.pi/2))*skew_symmetric([0,1,0])@skew_symmetric([0,1,0]))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]]
[[ 1.11022302e-16  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  1.11022302e-16]]


(b)

In [13]:
left = np.exp(skew_symmetric([1,0,0])+skew_symmetric([0,1,0]))
right = np.exp(skew_symmetric([1,0,0]))@np.exp(skew_symmetric([0,1,0]))
print(left)
print(right)
print(np.allclose(left,right))

[[1.         1.         2.71828183]
 [1.         1.         0.36787944]
 [0.36787944 2.71828183 1.        ]]
[[2.36787944 3.         4.71828183]
 [2.13533528 2.36787944 4.08616127]
 [4.08616127 4.71828183 6.43656366]]
False


4.

In [20]:
p_prime = R.from_quat([-1/math.sqrt(2),0,0,-1/math.sqrt(2)])
q_prime = R.from_quat([0,-1/math.sqrt(2),0,-1/math.sqrt(2)])
print(p_prime.as_euler('xyz',True))
print(q_prime.as_euler('zxy',True)) #zxy order
print(p_prime.as_rotvec())
print(q_prime.as_rotvec())

[90.  0.  0.]
[ 0.  0. 90.]
[ 1.57079633 -0.         -0.        ]
[-0.          1.57079633 -0.        ]


In [22]:
r_prime = R.from_quat([-1/math.sqrt(5),0,0,-2/math.sqrt(5)])
print(r_prime.as_euler('xyz',True))
print(r_prime.as_rotvec())
print(r.as_rotvec())

[53.13010235  0.          0.        ]
[ 0.92729522 -0.         -0.        ]
[0.92729522 0.         0.        ]


Problem 4

2.

$$ T(\boldsymbol{\theta}) = \left[ \begin{matrix}
cos(\theta_1 +\theta_2) & sin(\theta_1 +\theta_2) & 0 & 2sin(\theta_1 +\theta_2) + 1.6sin(\theta_1)\\
-sin(\theta_1 +\theta_2) & cos(\theta_1 +\theta_2) & 0 & 2cos(\theta_1 +\theta_2) + 1.6cos(\theta_1)\\
0 & 0 & 1 & -\theta_3 + 0.85\\
0 & 0 & 0 & 1 \\ 
\end{matrix} \right] $$ 

4.

$$
q^e = \left[ \begin{matrix}
x_e\\ y_e\\ z_e
\end{matrix}\right], \quad
q^s = \left[ \begin{matrix}
x_s\\ y_s\\ z_s
\end{matrix}\right]
$$


$$
\left[ \begin{matrix}
x_s\\ y_s\\ z_s \\1
\end{matrix}\right]=
T_{s \rarr e}(\boldsymbol{\theta}) \left[ \begin{matrix}
x_e\\ y_e\\ z_e \\1
\end{matrix}\right],
$$

$$
\left[ \begin{matrix}
x_s\\ y_s\\ z_s \\1
\end{matrix}\right]=
\left[ \begin{matrix}
2sin(\theta_1 +\theta_2) + 1.6sin(\theta_1) + x_ecos(\theta_1 +\theta_2)+y_esin(\theta_1 +\theta_2)\\
2cos(\theta_1 +\theta_2) + 1.6cos(\theta_1) +y_ecos(\theta_1 +\theta_2)-x_esin(\theta_1 +\theta_2) \\
z_e -\theta_3 + 0.85 \\
1
\end{matrix} \right]
$$

$$
\left[ \begin{matrix}
x_e\\ y_e\\ z_e \\ 1
\end{matrix}\right]
=
T_{s \rarr e}^{-1}(\boldsymbol{\theta}) 
\left[ \begin{matrix}
x_s\\ y_s\\ z_s \\1
\end{matrix}\right], \quad 
T_{s \rarr e}^{-1} = 
\left[ \begin{matrix}
cos(\theta_1 +\theta_2) & -sin(\theta_1 +\theta_2) & 0 & 1.6sin(\theta_2)\\
sin(\theta_1 +\theta_2) & cos(\theta_1 +\theta_2) & 0 & -1.6cos(\theta_2)-2\\
0 & 0 & 1 & \theta_3 - 0.85 \\
0 & 0 & 0 & 1
\end{matrix} \right]
$$

$$
\left[ \begin{matrix}
x_e\\ y_e\\ z_e \\1
\end{matrix}\right]
=
\left[ \begin{matrix}
1.6sin(\theta_2)+x_xcos(\theta_1 +\theta_2)-y_ssin(\theta_1 +\theta_2)\\
y_scos(\theta_1 +\theta_2)-1.6cos(\theta_2) + x_ssin(\theta_1 +\theta_2)-2 \\
\theta_3 + z_s - 0.85 \\
1
\end{matrix} \right]
$$